package com.example.gddemo.database.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.gddemo.entity.CreditCard;
import com.example.gddemo.entity.IdCard;
import com.example.gddemo.entity.Student;
import com.example.gddemo.entity.StudentAndTeacherBean;
import com.example.gddemo.entity.Teacher;

import com.example.gddemo.database.greenDao.db.CreditCardDao;
import com.example.gddemo.database.greenDao.db.IdCardDao;
import com.example.gddemo.database.greenDao.db.StudentDao;
import com.example.gddemo.database.greenDao.db.StudentAndTeacherBeanDao;
import com.example.gddemo.database.greenDao.db.TeacherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig creditCardDaoConfig;
    private final DaoConfig idCardDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig studentAndTeacherBeanDaoConfig;
    private final DaoConfig teacherDaoConfig;

    private final CreditCardDao creditCardDao;
    private final IdCardDao idCardDao;
    private final StudentDao studentDao;
    private final StudentAndTeacherBeanDao studentAndTeacherBeanDao;
    private final TeacherDao teacherDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        creditCardDaoConfig = daoConfigMap.get(CreditCardDao.class).clone();
        creditCardDaoConfig.initIdentityScope(type);

        idCardDaoConfig = daoConfigMap.get(IdCardDao.class).clone();
        idCardDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        studentAndTeacherBeanDaoConfig = daoConfigMap.get(StudentAndTeacherBeanDao.class).clone();
        studentAndTeacherBeanDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        creditCardDao = new CreditCardDao(creditCardDaoConfig, this);
        idCardDao = new IdCardDao(idCardDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        studentAndTeacherBeanDao = new StudentAndTeacherBeanDao(studentAndTeacherBeanDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);

        registerDao(CreditCard.class, creditCardDao);
        registerDao(IdCard.class, idCardDao);
        registerDao(Student.class, studentDao);
        registerDao(StudentAndTeacherBean.class, studentAndTeacherBeanDao);
        registerDao(Teacher.class, teacherDao);
    }
    
    public void clear() {
        creditCardDaoConfig.clearIdentityScope();
        idCardDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        studentAndTeacherBeanDaoConfig.clearIdentityScope();
        teacherDaoConfig.clearIdentityScope();
    }

    public CreditCardDao getCreditCardDao() {
        return creditCardDao;
    }

    public IdCardDao getIdCardDao() {
        return idCardDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public StudentAndTeacherBeanDao getStudentAndTeacherBeanDao() {
        return studentAndTeacherBeanDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

}
